sudo: required
dist: trusty
group: edge
language: scala
jdk:
  - oraclejdk9
scala:
   - 2.11.8
   - 2.12.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
